# yum and service modules with sudo access
# using selinux module to set the target to permissive mode

---
- hosts: app
  become: yes
  vars: 
    username: ravi
    doc_root: /var/www/html
  tasks:

# This task will install apache http server
  - name: Install Apache
    yum:
      name: httpd
      state: present

# This task will start apache http server
  - name: Start Apache
    service:
      name: httpd 
      state: started 
      enabled: yes

# This will copy site file
  - name: Copy index template from templates
    template: 
      src: 24/templates/index.j2
      dest: "{{ doc_root }}/index.html"

