# yum and service modules with sudo access
# Now i don't want the task configure port 8081 and restarting service to run
---
- hosts: web
  become: yes
  tasks:

# This task will install apache http server
  - name: Install Apache
    yum:
      name: httpd
      state: present
    tags: install

# This task will start apache http server
  - name: Start Apache
    service:
      name: httpd 
      state: started 
      enabled: yes
    tags: start

# This task will copy custom httpd.conf file to /etc/httpd/conf/httpd.conf
  - name: Copy apache config with port 8081 defined
    copy: 
      src: 12/httpd.conf 
      dest: /etc/httpd/conf/httpd.conf

# This task will restart apache http server
  - name: Restart Apache
    service:
      name: httpd 
      state: restarted

